name: dp-dino
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch3d
  - numpy
  - numba
  - scipy
  - py-opencv
  - cffi
  - ipykernel
  - matplotlib
  - zarr
  - numcodecs
  - h5py
  - hydra-core
  - einops
  - tqdm
  - dill
  - scikit-video
  - scikit-image
  - gym
  - pymunk
  - wandb
  - threadpoolctl
  - shapely
  - cython
  - imageio
  - imageio-ffmpeg
  - termcolor
  - tensorboard
  - tensorboardx
  - psutil
  - click
  - boto3
  - accelerate
  - datasets
  - av
  - cmake
  # trick to avoid cpu affinity issue described in https://github.com/pytorch/pytorch/issues/99625
  - llvm-openmp
  - pip:
    # PyTorch with CUDA support - install manually after environment creation:
    # pip uninstall torch torchvision -y
    # pip install torch torchvision --index-url https://download.pytorch.org/whl/cu124
    - ray[default,tune]
    # requires mujoco py dependencies libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
    - free-mujoco-py
    - pygame
    - pybullet-svl==3.1.6.4
    - robosuite
    - robomimic
    - pytorchvideo
    # pip package required for jpeg-xl
    - imagecodecs
    - diffusers
    - transformers
    - torchmetrics
    - r3m @ https://github.com/facebookresearch/r3m/archive/b2334e726887fa0206962d7984c69c5fb09cceab.tar.gz
    - dm-control
